---
deployment:
  tasks:
    - export DEPLOYPATH=/home/oqfbbllj/public_html/
    - /home/oqfbbllj/repositories/auesome team.html $DEPLOYPATH
		- /home/oqfbbllj/repositories/auesome app.js $DEPLOYPATH
		- /home/oqfbbllj/repositories/auesome index.html $DEPLOYPATH
		- /home/oqfbbllj/repositories/auesome package-lock.json $DEPLOYPATH
		- /home/oqfbbllj/repositories/auesome package.json $DEPLOYPATH
		- /home/oqfbbllj/repositories/auesome README.md $DEPLOYPATH
